version = 0.1
[default.deploy.parameters]
stack_name = "company-feedback-backend-sam"
resolve_s3 = true
s3_prefix = "company-feedback-backend-sam"
region = "us-east-1"
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
parameter_overrides = "AppName=\"company-feedback\" AppEnv=\"dev\""
image_repositories = []
